### ISSUE TITLE
Put back RubyProf for MRI optimization.

### ISSUE THREAD

**Issue by digitalextremist** [socketry/timers#54]
Per @ioquatix, put `RubyProf` back for MRI exclusively.

**Comment by ioquatix** [comment]
Yes, please do this :) Thanks.

Anyone doing any kind of serious work on timers would need to profile like crazy. It was a lot of effort to improve the performance of timers and the profiling code represents a significant investment of time.

I can tell anyone with the time specifically where I think work is required. But right now, I don't think the pay off is big enough because there are other issues with performance in celluloid and celluloid-io which dwarf the current timers implementation.

I believe we should be adding a specific set of specs to celluloid, celluloid-io and other gems of core importance, which includes RubyProf and allow us to easily see any performance issues. I haven't had time to work on the performance of celluloid-io yet, but I have done things along these lines to RubyDNS/celluloid-dns (don't think this is committed into the core repo).

Why I think this is important is that A) it allows performance to be empirically observed. and B) it shows that the project is committed to performance. C) Having some performance metrics printed out in travis (even if something very simple like benchmark) allows you to see between Ruby implementations the performance characteristics and changes over time. Ideally, there could be a system like coveralls which tracks performance per commit?

**Comment by digitalextremist** [comment]
I agree with you completely @ioquatix... on all points:

- Adding `RubyProf` back, here.
- Having an obvious performance-forward stance.
- Adding it ( and equivalents which support other rubies ) to celluloid/core.

I am starting a NoSQL abstraction layer for Ruby also, building Celluloid::IO into that, and it would be awesome to benchmark different databases, and different rubies, empirically.

**Comment by ioquatix** [comment]
if you are doing some kind of no-sql thing, check out what I did, relaxo. I've been thinking it could be a good idea to make it more generic.

https://github.com/ioquatix/relaxo

**Comment by digitalextremist** [comment]
Thank you for linking that, I saw it before and then forgot what it was called and lost it. I was searching the CouchDB world for that. I knew you'd done pretty outstanding work in NoSQL. The diversity *and* depth have is very rare and impressive. I'll put CouchDB into the initial roadmap for `Nada` then.

**Comment by digitalextremist** [comment]
Oh, sorry, I just realized I never linked the abstraction layer library, and then mentioned it by name as if I had. That's here:

https://github.com/abstractive/nada

( Spanish word for "nothing", "any", "nil", "naught", and "none" ... depending on context )
