### ISSUE TITLE
Minor version 4.3.1 has ruby version >=2.5 as dependency

### ISSUE THREAD

**Issue by brandsr** [socketry/timers#72]
When a ruby version of 2.2.1 is supported and the next minor release is ruby 2.5, it should NOT be a minor version release!!!!!!

**Comment by ioquatix** [comment]
Fair enough, is this breaking something? Are you using an unsupported Ruby release? Is some kind of bundle update command now failing? It seems weird to me because I'd expect your bundle environment to pull the latest version of the gem that works.

**Comment by brandsr** [comment]
We are using ruby 
`/service # ruby -v
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-linux-musl]`
We have a local gem in our environment, which depends on timers with `~> 4.1`, When we build again, timers failes so our gem fails also. Now we MUST use ruby 2.5 to use our own locally build gem, just because of this breaking version.

**Comment by brandsr** [comment]
Of course the solution is to pin at a lower version level, but still: from `4.3.0` supporting ruby `>2.2.1` to timers `4.3.1` and breaking all versions of ruby `<2.5`, seems as a bug to resolve.

**Comment by brandsr** [comment]
It would be easier for users to major version upgrade to `5.0.0`, without breaking things for (our ancient) users.

**Comment by colby-swandale** [comment]
@ioquatix the `required_ruby_version` & `required_rubygems_version` fields in the gemspec are not part of the resolution calculation in rubygems/bundler, they are checked only during install time. We have tickets to add these fields into the resolution process https://github.com/rubygems/rubygems/issues/3089

**Comment by ioquatix** [comment]
I have release 4.3.2 which removes the explicit dependency on Ruby >= 2.5 however I could not easily test the gem on 2.2 - 2.4 due to the gemspec using `Dir.glob` with a base path which is not supported on older Rubies. I'm not willing to spent a huge amount of effort testing on older gems. I don't plan on breaking this gem, but I also won't be actively testing on EOL Rubies. It makes sense that bundler supports this field in it's resolution process which would alleviate these kinds of issues.
